name: bfalg-shape
channels:
dependencies:
    - six==1.10.0
    - pyproj==1.9.5.1
    - Pillow==4.2.0
    - olefile==0.44
    - numpy==1.13.0
    - pip:
      - "git+https://github.com/gipit/gippy.git@v1.0.0b8#egg=gippy-1.0.0b8"
      - "eyeD3==0.8"
      - "OSR==0.0.1"
      - "pyglet==1.1.4"

