name: bfalg-shape
channels:
  - https://proxy:proxy@nexus.devops.geointservices.io/content/repositories/beachfront-conda
dependencies:
    - pillow=4.2.1
    - pyproj=1.9.5.1
    - gdal=2.1.3
    - gippy=1.0.0b8
    - requests=2.18.1
