name: bfalg-shape
channels:
  - https://conda-channel.int.geointservices.io
  - conda-forge
  - bioconda
  - defaults
dependencies:
    - numpy
    - potrace
    - pypotrace
    - pillow
    - pyproj
    - libagg=2.5.0
    - fiona=1.7.4
    - gdal=2.1.3
    - gippy
    - pip:
      - eyed3
