name: bfalg-shape
channels:
  - CHANNEL
  - conda-forge
  - bioconda
  - defaults
dependencies:
    - conda=4.3.22
    - numpy
    - potrace
    - pypotrace
    - pillow
    - pyproj
    - libagg=2.5.0
    - fiona=1.7.4
    - gdal=2.1.3
    - gippy
    - pip:
      - eyed3
